on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/5531b1b9db4f7db51128c2cd952aa579
          gist_title: 3-Corrimiento-LED-CCS-4550.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/Corrimiento de bits.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/7ff80a956101d17e69a87ad060d0625f
          gist_title: 3-Corrimiento-LED-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/Corrimiento de bits.c
          file_encoding: WINDOWS-1252